name: repository_interface
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart:

  applog:
    git:
      url: https://github.com/Stefano-Trinca/applog.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
